services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  user-service:
    build: ./user-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=javamicroservice
      - DB_USER=postgres
      - DB_PASSWORD=1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
    ports:
      - "8081:8080"
    networks:
      - backend

  order-service:
    build: ./order-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=javamicroservice
      - DB_USER=postgres
      - DB_PASSWORD=1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
    ports:
      - "8082:8080"
    networks:
      - backend

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - user-service
      - order-service
    networks:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: javamicroservice
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge