server:
  port: 8080
spring:
  application:
    name: user_service
  datasource:
    url: jdbc:h2:mem:user_service;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8755/eureka
